name: Push to GCR GitHub Action

on: [workflow_dispatch]

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: sonorous-parsec-228911
          image_name: test-cloudrun

  deploy-cloudrun:
    needs: [build-and-push-to-gcr]
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.6.0
        with:
          image: gcr.io/sonorous-parsec-228911/test-cloudrun
          service: hello-cloud-run

      - name: Use Output
        run: curl "${{ steps.deploy.outputs.url }}"
